
version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: fct_sales_transactions
    columns:
      - name: transaction_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: transaction_date
        tests: [not_null]
